### PR TITLE
CUP Launchers: Backblast

### PR DESCRIPTION
**Pull request by Winter259**
Here's the non-disposables patches for CUP Launchers. We did a fair amount of research regarding backblast range and angle but we couldn't find accurate war time values for every launcher so we had to improvise on some of the configs.

### CODE REVIEW

**Comment by jonpas** [comment]
There is a merge conflict, apparently with the latest commit 48945a4d21ccec9a0b686132d1cd0ad0db2e25f5 where you added yourself to the Authors file, you already did that in previous pull request.

**Comment by Winter259** [comment]
Ah yes, this arose because I'm basing all 3 of my branches (top down, backblast and disposable) off the (now old) master branch. Can you resolve it or shall I remove it from my branch?

**Comment by jonpas** [comment]
I can't, I don't have privileges to do that in this repository. You can revert last commit and that should do it, otherwise someone will come here and let you know.

**Comment by esteldunedain** [comment]
Don't worry about the conflicts. I can solve those; is this ready for merging?

**Comment by Winter259** [comment]
The values might need fine tuning in the future as we haven't had an opportunity to do some session scale testing yet, but the configs work as I tested each one.

**Comment by esteldunedain** [comment]
Thanks again

**Comment by Winter259** [comment]
No problem. Next one will be M136, RPG18 and CUP's NLAW with disposable included.

**Comment by esteldunedain** [comment]
Excellent; keep them coming!

**Pull request merged**
