### PR TITLE
CUP Modularity

### PR DESCRIPTION
**Pull request by jonpas**
Should all be working, checked for syntax errors, but didn't test in-game.

Changed;
- Split into PBOs (obviously)
- Renamed to contain `CUP_Weapons` as `CUP` only can mean more when/if other CUP packs are released, this does mean names are quite long now though
- Something was in ANSI, can't remember what, changed it to UTF-8 w/o BOM
- Added newlines for git merge

Questions:
- Should all PBOs require CUP_Weapons_Ammunition?
- Should all PBOs require AGM_Comp_CUP_Weapons_Ammunition?

### CODE REVIEW

**Comment by esteldunedain** [comment]
Gj! 

Questions:

> Should all PBOs require CUP_Weapons_Ammunition?
>Should all PBOs require AGM_Comp_CUP_Weapons_Ammunition?

Not really, but I would leave that so people don't forget to add the AGM_Comp_CUP_Weapons_Ammunition pbo, which enables overheating

**Comment by jonpas** [comment]
Cool, so `AGM_BulletMass` basically enables overheating by giving the bullet "mass"?

I am asking because in my community we don't use overheating, so I know if it's important we use `AGM_BulletMass` or not.

**Comment by esteldunedain** [comment]
> Cool, so AGM_BulletMass basically enables overheating by giving the bullet "mass"?

Exactly

> in my community we don't use overheating

Man, you should really give it a try. It's much much better after 0.94. :grinning:

**Comment by jonpas** [comment]
Perfect, thanks!

Yep I agree, but we have some form of democracy so what I did was just make a poll... well it was voted against, even though I stressed out a lot that it was greatly improved, but what can we do. :P

**Comment by esteldunedain** [comment]
> but we have some form of democracy so what I did was just make a poll... well it was voted against, even though I stressed out a lot that it was greatly improved, but what can we do

coup d'état? :wink:

**Comment by jonpas** [comment]
Heh, I am a pilot so I don't really worry about it. :D

**Pull request merged**
