### PR TITLE
CUP Javelin Top Down Attack

### PR DESCRIPTION
**Pull request by Winter259**
I wrote a config for CUP's Javelin to include Top Down attack. I'll be submitting pull requests for backblast for all applicable launchers & for disposable for M136 & RPG18 soon.

### CODE REVIEW

**Comment by jonpas** [comment]
Are `AGM_Comp_CUP_Weapons_Ammunition` and `CUP_Weapons_Ammunition` needed for this to work? I am pretty sure they are safe to be removed.

Can you also apply [AGM Coding Guidelines](https://github.com/KoffeinFlummi/AGM/wiki/Coding-Guidelines) (tabs -> double spaces)?

Otherwise looks good!

**Comment by Winter259** [comment]
Excuse the tabs, force of habit.

I tested the javelin without the PBOs you mentioned in the required line and it worked just as good.

**Comment by jonpas** [comment]
Perfect, keep it on version 1.0 though, at least for now, I don't believe if it was decided how releases will go with this project (if at all).

**Comment by Winter259** [comment]
No problem re: version numbers. Thanks for reviewing!

**Comment by esteldunedain** [comment]
:+1: Thanks

**Comment by jonpas** [comment]
Good job, thanks!

**Pull request merged**
